### ISSUE TITLE
address `dotenv` confusion

### ISSUE THREAD

**Issue by simsong** [donaldm314/dropbox-commandline-oauth-refresh#1]
This is a great resource. Unfortunately, `dotenv` caused me a lot of confusion, as `pip install dotenv` doesn't work. It took a while for me to discover that I had to do a `pip install python-dotenv`.

Would you be open to a PR that either:
1. Rewrites this so that dotenv is not required
2. Adds a `requirements.txt` file so that it's clear how to install `dotenv`?

**Comment by donaldm314** [comment]
Oh, that's excellent feedback, thank you! I prefer your second suggestion and would gladly accept that PR.

**Comment by simsong** [comment]
Great. if you wish, I can add also give you a small demo program that lists all of the files and downloads one. It's a useful thing to show, I think.

**Comment by simsong** [comment]
(but that would be a seperate PR.)

**Comment by donmurray-suncor** [comment]
Sounds great, Simson, yes to both PRs!
